# Generated by Django 5.2 on 2025-05-12 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='discription',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='writer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='categories_tags',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='discription',
            field=models.CharField(default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_movie_id', to='movie_review.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user_id', to='movie_review.users')),
            ],
        ),
    ]
