# Generated by Django 5.2 on 2025-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0002_rename_discription_reviews_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.FileField(null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.FileField(null=True, upload_to='media/img'),
        ),
    ]
