# Generated by Django 5.2 on 2025-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0003_alter_movies_photo_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default='2025-5-14'),
        ),
    ]
