# Generated by Django 5.2 on 2025-05-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0006_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='secret',
            field=models.CharField(default='', max_length=255),
        ),
    ]
